### PR TITLE
v2.0.1

### PR DESCRIPTION
**Pull request by coltoneshaw**
Fixing bug with 3C API

### CODE REVIEW

**Comment by mfread** [comment]
Downloaded 2.0.1. Ran installer exe (presumably it over-writes my previous 2.0.0 install). 3CPM started. No active deals shown. When to setup. Tested API (not a new API - the one I was using with 2.0.0). No errors but Enabled switched to 'off' position when I tested the API. Enabled the setting. Tried to refresh active deals screen - nada. Deleted cache and retired - nada.

Went to Console. Found this:

react.development.js:220 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `CustomTable`. See https://reactjs.org/link/warning-keys for more information.
    at div
    at CustomTable (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:476076:24)
    at div
    at DealsTable (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:478726:23)
    at div
    at ActiveDealsPage (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:478639:81)
    at Route (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:431161:29)
    at div
    at MainWindow (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:480996:59)
    at div
    at Router (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:430792:30)
    at HashRouter (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:430454:35)
    at App (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:482635:60)
    at ThemeEngine (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:476894:24)
    at Provider (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:428121:20)
    at LocalizationProvider (file:///C:/Users/Mark/AppData/Local/Programs/3c-portfolio-manager/resources/app.asar/dist/renderer.js:243899:5)

What do I try next? Un-install then re-install?

Cheers,
Mark

**Comment by coltoneshaw** [comment]
Odd. Can someone try menu > help > reset profile. Then sync again? My test had it but it was a fresh database. I’ll get another fix out this morning if that’s the fix

**Comment by bgratt** [comment]
I tried that as well, but still it's the same result.

**Comment by mfread** [comment]
Downloaded and installed 2.0.2 on Win10. Working now thanks Colton. Time to buy you a coffee I think :)

I'll keep a watch on it.

**Comment by coltoneshaw** [comment]
Fantastic!! Be on the lookout for more. A lot incoming hopefully 😉

**Comment by bgratt** [comment]
Yes, its working again. Thanks for all your efforts @coltoneshaw.

**Pull request merged**
